---
version: "3"

# silent: true

includes:
  # c: https://raw.githubusercontent.com/standardloop/taskfiles/refs/heads/main/c.yml # can pin in future
  c: ../taskfiles/c.yml

vars:
  CC: /opt/homebrew/opt/llvm/bin/clang -I/usr/local/include
  DYN_LIBS_USED: "-lstandardloop-logger -lstandardloop-collections -lstandardloop-util"
  TEST_EXECUTABLE_NAME: test
  SOURCE_FILES:
    - yaml.c
    - parser.c
    - lexer.c
    - dynstring.c
  TEST_SOURCE_FILES:
    - lexer.test.c
  # for releasing
  DYLIB_NAME: libstandardloop-yaml.dylib
  DYLIB_HEADER: yaml.h

tasks:
  list:
    desc: "Lists all the tasks available to run."
    cmds:
      - yq '.tasks | to_entries | .[] | "* " + .key + ":\t" + (.value.desc // "")' Taskfile.yml | column -t -s $'\t'

  default:
    desc: "Builds and runs the test program."
    cmds:
      - task: test:build

  dependencies:
    desc: "Downloads C program dependencies."
    cmds:
      - task: c:dependencies:logger:latest
      - task: c:dependencies:util:latest
      - task: c:dependencies:collections:latest

  release:
    desc: "Release the dylib, used by GitHub actions."
    deps:
      - dependencies
    cmds:
      - task: c:release

  test:build:
    desc: "Builds the test program."
    deps:
      - dependencies
      - c:dependencies:testing
    cmds:
      - task: c:test:build

  test:run:
    desc: "Runs the test program."
    aliases:
      - test
    deps:
      - test:build
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}

  test:build-sanitize:
    desc: "Builds the test program with address sanitizers."
    deps:
      - dependencies
      - c:dependencies:testing
    cmds:
      - task: c:test:build-sanitize

  test:run-sanitize:
    desc: "Runs the test program with address sanitizers."
    aliases:
      - sanitize
    deps:
      - test:build-sanitize
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}-sanitize

  clean:
    desc: "Cleans binary files."
    deps:
      - c:test:clean

  fmt:
    desc: "Formats the C code with the `.clang-format` file."
    deps:
      - c:fmt

  docs:
    desc: "Generate docs/index.md and the task list in README.md"
    deps:
      - c:docs

  test:leaks:
    aliases:
      - leaks
    desc: "Run macOS leaks on the test program."
    deps:
      - test:build
    vars:
      DYLIBS:
        [
          "libstandardloop-logger.dylib",
          "libstandardloop-util.dylib",
          "libstandardloop-collections.dylib",
          "libstandardloop-testing.dylib",
        ]
    cmds:
      - |
        {{range .DYLIBS}}
        cp {{$.DYLIB_PATH}}{{.}} . {{end}}
        leaks --atExit -- ./{{.TEST_EXECUTABLE_NAME}}
        {{range .DYLIBS}}
        rm {{.}} {{end}}
